jobs:
#- job: macOS
#  pool:
#    vmImage: 'macOS-10.13'
#  steps:
#  - template: build.yml # Template reference#
#
#- job: Linux
#  pool:
#    vmImage: 'Ubuntu-16.04'
#  steps:
#  - template: build.yml # Template reference
#
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: build.yml # Template reference
